org: kdgromova
app: birds-api
service: birds-api
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - arn:aws:dynamodb:us-east-1:624173895702:table/bird-feeder-db
        - arn:aws:dynamodb:us-east-1:624173895702:table/bird-feeder-db/index/SK-PK

functions:
  get-birds:
    handler: handler.get_birds
    events:
      - httpApi:
          path: /birds
          method: get
  get-bird-videos:
    handler: handler.get_bird_videos
    events:
      - httpApi:
          path: /birds/{species}
          method: get
  get-video:
    handler: handler.get_video
    events:
      - httpApi:
          path: /videos/{video}
          method: get
plugins:
  - serverless-python-requirements
